name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18.18.2
        uses: actions/setup-node@v2
        with:
          node-version: v18.18.2
      - name: npm install and test
        run: |
         yarn install
          yarn run ci:test
          yarn run e2e
